// Generated by Selenium IDE

import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.testng.annotations.AfterMethod;
import org.testng.annotations.BeforeMethod;
import org.testng.annotations.Test;
public class TestloginTest {
   WebDriver wd;

//  private Map<String, Object> vars;
//  JavascriptExecutor js;
  @BeforeMethod
  public void setUp() {
    wd = new ChromeDriver();
  //  js = (JavascriptExecutor) wd;
  //  vars = new HashMap<String, Object>();
  }
  @AfterMethod
  public void tearDown() {
    wd.quit();
  }
  @Test
  public void testlogin() {
    wd.get("https://www.saucedemo.com/");
    wd.manage().window().maximize();
    wd.findElement(By.cssSelector(".login_credentials_wrap-inner")).click();
    wd.findElement(By.cssSelector("*[data-test=\"username\"]")).click();
    wd.findElement(By.cssSelector("*[data-test=\"username\"]")).sendKeys("standard_user");
    wd.findElement(By.cssSelector(".login_password")).click();
    wd.findElement(By.cssSelector(".login_password")).click();
    wd.findElement(By.cssSelector("*[data-test=\"password\"]")).click();
    wd.findElement(By.cssSelector("*[data-test=\"password\"]")).sendKeys("secret_sauce");
    wd.findElement(By.cssSelector("*[data-test=\"login-button\"]")).click();
    wd.findElement(By.cssSelector(".inventory_item:nth-child(2) > .inventory_item_description")).click();
  }
}
